# Generated by Django 4.2.1 on 2023-05-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumnail',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
