# Generated by Django 4.2.1 on 2023-05-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_post_thumnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumnail',
            field=models.ImageField(blank=True, default='Some string', upload_to='images'),
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='images')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.post')),
            ],
        ),
    ]
